name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REPOSITORY: hello-world-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${IMAGE_TAG}

        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

        echo "::set-output name=image_uri::$IMAGE_URI"

    - name: Deploy to ECS
      env:
        AWS_REGION: us-east-1
        CLUSTER_NAME: hello-world-cluster
        SERVICE_NAME: hello-world-service
        TASK_FAMILY: hello-world-task
        CONTAINER_NAME: hello-world-app
        IMAGE_URI: ${{ steps.build-image.outputs.image_uri }}
      run: |
        # Get the current task definition
        TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY)
        TASK_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r .taskDefinition.taskRoleArn)
        EXECUTION_ROLE_ARN=$(echo $TASK_DEFINITION | jq -r .taskDefinition.executionRoleArn)
        CONTAINER_DEFINITIONS=$(echo $TASK_DEFINITION | jq .taskDefinition.containerDefinitions)
        
        # Update the container definitions with the new image
        UPDATED_CONTAINER_DEFINITIONS=$(echo $CONTAINER_DEFINITIONS | jq '.[0].image = "'$IMAGE_URI'"')
        
        # Register the new task definition
        NEW_TASK_DEFINITION=$(aws ecs register-task-definition \
          --family $TASK_FAMILY \
          --task-role-arn $TASK_ROLE_ARN \
          --execution-role-arn $EXECUTION_ROLE_ARN \
          --network-mode "awsvpc" \
          --container-definitions "$UPDATED_CONTAINER_DEFINITIONS" \
          --requires-compatibilities "FARGATE" \
          --cpu "256" \
          --memory "512")

        # Update the ECS service to use the new task definition
        NEW_TASK_REVISION=$(echo $NEW_TASK_DEFINITION | jq -r .taskDefinition.revision)
        aws ecs update-service \
          --cluster $CLUSTER_NAME \
          --service $SERVICE_NAME \
          --task-definition $TASK_FAMILY:$NEW_TASK_REVISION
